### ISSUE TITLE
Generating markdown from yaml fails

### ISSUE THREAD

**Issue by koustuvsinha** [mxl/swagger2markup-cli#1]
Hi, I am trying to use the CLI to convert my swagger 2.0 yaml into a markdown document. On executing the following command : 

```java
java -jar build/libs/swagger2markup-cli-0.0.1.jar -v generate -i ~/Downloads/swagger.yaml -l yaml -o ~/Documents
```

I get the following error : 

```java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from /home/koustuv/Downloads/swagger.yaml
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant io.github.robwin.markup.builder.MarkupLanguage.YAML
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.github.robwin.markup.builder.MarkupLanguage.valueOf(MarkupLanguage.java:28)
	at me.ledin.swagger2markup.Application$Generate.run(Application.java:59)
	at me.ledin.swagger2markup.Application.main(Application.java:17)
```

**Comment by koustuvsinha** [comment]
Sorry, my bad. Had given `yaml` in the language part, it should be the generated output language not the input one. Just mention it in the docs! :)
